vim.keymap.set('n', '<Esc>', '<cmd>nohlsearch<CR>')
vim.keymap.set('n', '<leader>q', '<cmd>q<CR>', { desc = '[Q]uit neovim' })
vim.keymap.set('n', '<leader>s', '<cmd>w<CR>', { desc = '[S]ave current buffer' })
vim.keymap.set('n', '<leader>h', '<C-w><C-h>', { desc = 'Move focus to the left window' })
vim.keymap.set('n', '<leader>l', '<C-w><C-l>', { desc = 'Move focus to the right window' })
vim.keymap.set('n', '<leader>j', '<C-w><C-j>', { desc = 'Move focus to the lower window' })
vim.keymap.set('n', '<leader>k', '<C-w><C-k>', { desc = 'Move focus to the upper window' })
vim.keymap.set('n', 'j', 'gj')
vim.keymap.set('n', 'k', 'gk')
vim.keymap.set('n', '<S-j>', '<cmd>m .+1<CR>==')
vim.keymap.set('n', '<S-k>', '<cmd>m .-2<CR>==')
vim.keymap.set('n', '<leader>hs', '<cmd>split<CR>', { desc = '[H]orizontal [S]plit' })
vim.keymap.set('n', '<leader>vs', '<cmd>vsplit<CR>', { desc = '[V]ertical [S]plit' })
vim.keymap.set('n', '<leader>+', '<cmd>resize +2<CR>')
vim.keymap.set('n', '<leader>_', '<cmd>resize -2<CR>')
vim.keymap.set('n', '<leader>=', '<cmd>vertical resize +2<CR>')
vim.keymap.set('n', '<leader>-', '<cmd>vertical resize -2<CR>')
vim.keymap.set('n', '<leader>bd', '<cmd>bdelete<CR>', { desc = '[B]uffer [D]elete' })
vim.keymap.set('v', '<S-k>', "<cmd>m '<-2<CR>gv=gv")
vim.keymap.set('v', '<S-j>', "<cmd>m '>+1<CR>gv=gv")
vim.keymap.set('i', 'jk', '<Esc>', { desc = 'Exit insert mode' })
vim.keymap.set('i', 'kj', '<Esc>', { desc = 'Exit insert mode' })
